site_name: Documentation Test
site_url: https://ossirytk.github.io/documentation-test
repo_url: https://github.com/ossirytk/documentation-test
nav:
  - Home: index.md
  - Installation: installation.md
  - Coding:
      - Some Code Stuff: some_code_stuff.md
      - Some Other Code Stuff: some_other_code_stuff.md
  - About: about.md
  - License: UNLICENSE.md
theme: readthedocs
